// Stability AI image generation implementation

export async function generateWithStability(
  apiKey: string, 
  model: string, 
  prompt: string, 
  width = 1024, 
  height = 1024
) {
  try {
    const engineId = model === 'stable-diffusion-v1-6' 
      ? 'stable-diffusion-v1-6' 
      : 'stable-diffusion-xl-1024-v1-0';

    const response = await fetch(
      `https://api.stability.ai/v1/generation/${engineId}/text-to-image`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'Accept': 'application/json',
        },
        body: JSON.stringify({
          text_prompts: [
            {
              text: prompt,
              weight: 1
            }
          ],
          cfg_scale: 7,
          height: height,
          width: width,
          samples: 1,
          steps: 30,
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      return { 
        error: `Stability AI error: ${response.status} - ${errorText}`, 
        status: response.status 
      };
    }

    const data = await response.json();
    
    if (data.artifacts && data.artifacts.length > 0) {
      const base64Image = data.artifacts[0].base64;
      return { imageUrl: `data:image/png;base64,${base64Image}` };
    } else {
      return { error: 'No image generated by Stability AI' };
    }

  } catch (error) {
    return { error: `Stability AI generation failed: ${error.message}` };
  }
}