/**
 * Supabase Client Configuration
 * This file is automatically generated. Do not edit it directly.
 * Contains the Supabase client instance with authentication and configuration
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/** Supabase project URL - points to the hosted database instance */
const SUPABASE_URL = "https://tbsgqvrfoljyjciflosl.supabase.co";

/** 
 * Supabase anonymous/public key for client-side operations
 * This key is safe to expose in client-side code as it only allows
 * operations that are explicitly permitted by Row Level Security (RLS) policies
 */
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRic2dxdnJmb2xqeWpjaWZsb3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzI1NzEsImV4cCI6MjA3MjY0ODU3MX0.SYoXicHxRzXjxnKSPvkSwylt4eFLeOQzehfPSlnJiqU";

/**
 * Usage example:
 * ```typescript
 * import { supabase } from "@/integrations/supabase/client";
 * 
 * // Use the client for database operations
 * const { data, error } = await supabase.from('table_name').select('*');
 * ```
 */

/**
 * Configured Supabase client instance
 * Includes TypeScript types for type-safe database operations
 * Configured with authentication settings for persistent sessions
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use browser's localStorage for session persistence
    storage: localStorage,
    // Keep user logged in across browser sessions
    persistSession: true,
    // Automatically refresh expired tokens
    autoRefreshToken: true,
  }
});